---
- name: Update SNMP 
  hosts: rtr1
  gather_facts: no
  tags: ansible_snmp
  tasks:
    - name: configure global bgp as 64496
      ios_bgp:
        config:
           bgp_as: 64496
           router_id: 192.0.2.1
           log_neighbor_changes: True
           neighbors:
             - neighbor: 203.0.113.5
               remote_as: 64511
               timers:
                 keepalive: 300
                 holdtime: 360
                 min_neighbor_holdtime: 360
             - neighbor: 198.51.100.2
               remote_as: 64498
           networks:
             - prefix: 198.51.100.0
               masklen: 24
             - prefix: 192.0.2.0
               masklen: 23
           address_family:
             - afi: ipv4
               safi: unicast
               redistribute:
                 - protocol: ospf
                   id: 223
                   metric: 10
        operation: merge
